'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CareLink.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AboutBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AboutBoxDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutBoxDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdvancedView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdvancedViewDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedViewDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalibrationDot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalibrationDot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalibrationDotRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalibrationDotRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalibrationNotReady() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalibrationNotReady", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalibrationUnavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalibrationUnavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CopyDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CopyDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExitDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExitDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExitFullScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExitFullScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExportData() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportData", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FeedbackSmile_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FeedbackSmile_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FeedbackSmile_16xDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FeedbackSmile_16xDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property High_Alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("High Alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InsulinVial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsulinVial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InsulinVial_Tiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsulinVial_Tiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Low_Alarm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Low Alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MealImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MealImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MealImageLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MealImageLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotificationAlert_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationAlert_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotificationAlertGray_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationAlertGray_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotificationAlertRed_16x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationAlertRed_16x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenFileDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenProjectFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenProjectFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OpenProjectFolderDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenProjectFolderDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryCritical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryCritical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpBatteryUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpBatteryUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpConnectivityToPhoneNotOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpConnectivityToPhoneNotOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpConnectivityToPhoneOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpConnectivityToPhoneOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpConnectivityToTransmitterNotOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpConnectivityToTransmitterNotOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpConnectivityToTransmitterOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpConnectivityToTransmitterOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PumpConnectivityToTransmitterUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PumpConnectivityToTransmitterUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains15_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains29_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains29_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains43_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains43_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains57_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains57_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains71_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains71_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemains85_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemains85_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReservoirRemainsUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReservoirRemainsUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectAllDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectAllDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SensorCommunicationLost() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SensorCommunicationLost", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SensorExpirationUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SensorExpirationUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SensorExpired() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SensorExpired", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SensorLifeNotOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SensorLifeNotOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SensorLifeOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SensorLifeOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield_Disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_Disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryCritical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryCritical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TransmitterBatteryUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TransmitterBatteryUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
