' Licensed to the .NET Foundation under one or more agreements.
' The .NET Foundation licenses this file to you under the MIT license.
' See the LICENSE file in the project root for more information.

Imports System.IO
Imports CareLink
Imports FluentAssertions
Imports Xunit

Public Class ValidateDiscoveryMappings

    <Fact>
    Public Async Function All_CountryCodes_Are_Present_In_Discovery() As Task
        Dim usDiscovery As DiscoveryRoot = Await GetDiscoveryDataAsync(countryCode:="US")
        Dim euDiscovery As DiscoveryRoot = Await GetDiscoveryDataAsync(countryCode:="EU")

        Dim allSupportedCodes As New HashSet(Of String)(comparer:=StringComparer.OrdinalIgnoreCase)

        Dim discoveries As New List(Of DiscoveryRoot) From {usDiscovery, euDiscovery}
        For Each discovery As DiscoveryRoot In discoveries
            For Each countryDict As Dictionary(Of String, CountryInfo) In discovery.SupportedCountries
                For Each kvp As KeyValuePair(Of String, CountryInfo) In countryDict
                    allSupportedCodes.Add(item:=kvp.Key)
                Next
            Next
        Next

        Dim missingPairs As New List(Of KeyValuePair(Of String, String))
        For Each kvp As KeyValuePair(Of String, String) In s_countryToCodeList
            Dim displayName As String = kvp.Key
            Dim code As String = kvp.Value
            If Not allSupportedCodes.Contains(item:=code) Then
                missingPairs.Add(item:=New KeyValuePair(Of String, String)(key:=displayName, value:=code))
            End If
        Next

        ' Write generated VB file with the unsupported country list to repo-local test output directory for manual review/merge
        ' Attempt to locate repository root by searching for the solution file upwards from the test execution directory.
        Dim repoRoot As String = Nothing
        Dim probeDir As String = AppContext.BaseDirectory
        Do While Not String.IsNullOrEmpty(value:=probeDir)
            If File.Exists(path:=Path.Combine(probeDir, "CareLink.slnx")) Then
                repoRoot = probeDir
                Exit Do
            End If
            Dim parent As DirectoryInfo =
                Directory.GetParent(path:=probeDir)
            If parent Is Nothing Then
                Exit Do
            End If
            probeDir = parent.FullName
        Loop

        Dim outDir As String =
            If(Not String.IsNullOrEmpty(value:=repoRoot),
               Path.Combine(repoRoot, "src", "TestProject", "TestOutputs"),
               Path.Combine(AppContext.BaseDirectory, "TestOutputs"))
        Directory.CreateDirectory(path:=outDir)
        Dim outFile As String = Path.Combine(outDir, "UnsupportedCountryCodes.generated.vb")

        Dim sb As New Text.StringBuilder()
        sb.AppendLine(value:="' Generated by ValidateDiscoveryMappings test")
        sb.AppendLine(value:="' Review and merge into src\CareLink\Extensions\UnsupportedCountryCodes.vb if appropriate")
        sb.AppendLine()
        sb.AppendLine(value:="Imports System.Collections.Generic")
        sb.AppendLine()
        sb.AppendLine(value:="Namespace CareLink.Extensions")
        sb.AppendLine()
        sb.AppendLine(value:="    Public Module UnsupportedCountryLists")
        sb.AppendLine()
        sb.AppendLine(value:="        Public ReadOnly s_UnsupportedCountrysWithCodeList As New Dictionary(Of String, String) From {")

        For i As Integer = 0 To missingPairs.Count - 1
            Dim p As KeyValuePair(Of String, String) = missingPairs(index:=i)
            Dim line As String = $"            {{""{p.Key }"", ""{p.Value }""}}{If(i < missingPairs.Count - 1, ",", String.Empty) }"
            sb.AppendLine(value:=line)
        Next

        sb.AppendLine(value:="        }")
        sb.AppendLine()
        sb.AppendLine(value:="    End Module")
        sb.AppendLine(value:="End Namespace")

        File.WriteAllText(path:=outFile, contents:=sb.ToString())

        Dim missingStrings As New List(Of String)()
        For Each p As KeyValuePair(Of String, String) In missingPairs
            missingStrings.Add(item:=$"{p.Value } ({p.Key })")
        Next

        missingStrings.Should().BeEmpty(because:=$"These country codes are not present in discovery SupportedCountries. Generated file: {outFile}")
    End Function

    <Fact>
    Public Async Function Discovery_Mappings_Are_Consistent() As Task
        ' Retrieve discovery for US and EU using existing helper which fetches live endpoints.
        Dim usDiscovery As DiscoveryRoot =
            Await GetDiscoveryDataAsync(countryCode:="US")
        Dim euDiscovery As DiscoveryRoot =
            Await GetDiscoveryDataAsync(countryCode:="EU")

        Dim discoveries As New List(Of DiscoveryRoot) From {
            usDiscovery,
            euDiscovery}

        For Each discovery As DiscoveryRoot In discoveries
            discovery.SupportedCountries.Should().NotBeNull(because:="supportedCountries should be present in discovery JSON")

            For Each countryDict As Dictionary(Of String, CountryInfo) In discovery.SupportedCountries
                For Each kvp As KeyValuePair(Of String, CountryInfo) In countryDict
                    Dim countryCode As String = kvp.Key

                    ' countryCode is an ISO code (e.g. "US"). Get the human-readable name and verify
                    Dim countryDisplayName As String = countryCode.GetCountryFromCode()

                    ' Ensure the name -> code dictionary contains the display name and maps back to the ISO code
                    s_countryToCodeList.ContainsKey(key:=countryDisplayName).Should().BeTrue(because:=$"Country display name '{countryDisplayName}' must exist in s_countryToCodeList")
                    s_countryToCodeList(key:=countryDisplayName).Should().Be(expected:=countryCode, because:=$"s_countryToCodeList('{countryDisplayName}') should map to code '{countryCode}'")

                    ' Use the helper to get the region display name string from the ISO code and verify server mapping exists
                    Dim region As String = countryCode.GetRegionFromCode()
                    s_regionToServerMapping.ContainsKey(key:=region).Should().BeTrue(because:=$"Region '{region}' for country '{countryDisplayName}' must be present in s_regionToServerMapping")
                Next
            Next

            ' CP entries should have a Region value that appears among the mapping values (e.g. "US","EU","CLINICAL")
            For Each cp As CPEntry In discovery.CP
                cp.Region.Should().NotBeNullOrWhiteSpace()
                Dim matched As Boolean = s_regionToServerMapping.ContainsValue(value:=cp.Region)
                matched.Should().BeTrue(because:=$"CP.Region '{cp.Region}' should be one of the server mapping values (e.g., 'US','EU','CLINICAL')")
            Next
        Next
    End Function

End Class
